---
abstract: 'Yet another (But Hopefully Better) Key-Value Storage mechanism'
author:
  - 'Kent Fredric <kentnl at cpan.org>'
generated_by: 'Dist::Zilla::Plugin::MetaYAML version 1.092310'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Data-Couplet
provides:
  Data::Couplet:
    file: lib/Data/Couplet.pm
    version: 0.0100
  Data::Couplet::Private:
    file: lib/Data/Couplet/Private.pm
    version: 0.0100
requires:
  Carp: 0
  Moose: 0.84
  Test::More: 0
  Test::use::ok: 0
  namespace::autoclean: 0
resources:
  repository: git://github.com/kentfredric/Data-Couplet.git
version: 0.0100
